api_platform:
    title: 'Ajeun-api'
    description: 'API du site Ajeun'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    collection:
        order_parameter_name: 'order'
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: itemPerPage